# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Tomer Kaftan'
tagline:          'Homepage'
description:      ''
url:              http://tomerk.github.io
baseurl:          /

author:
  name:           'Tomer Kaftan'
  url:            http://tomerk.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tomerk/tomerk.github.io

